wandb_version: 1

GPUs:
  desc: null
  value: 1
GPU Type:
  desc: null
  value: NVIDIA RTX A4000
Denoiser params:
  desc: null
  value: 50912291
Initial Predictor params:
  desc: null
  value: 50377091
Denoiser LR:
  desc: null
  value: 0.0001
Init Predictor LR:
  desc: null
  value: 0.0001
Batch size:
  desc: null
  value: 16
Sample size:
  desc: null
  value: 16
L2 Loss:
  desc: null
  value: false
L2 param:
  desc: null
  value: 0.0
Regularizer:
  desc: null
  value: true
Regularizer Threshold:
  desc: null
  value: 0.02
Dataset_t:
  desc: null
  value: /home/mr6744/gopro2/
Dataset_v:
  desc: null
  value: /home/mr6744/gopro2/
Path:
  desc: null
  value: /home/mr6744/ckpts/08152023_155000
Port:
  desc: null
  value: '50'
Ckpt step:
  desc: null
  value: 0
Ckpt path:
  desc: null
  value: ''
Ckpt metrics:
  desc: null
  value: false
Workers:
  desc: null
  value: 8
Dataset multiplier:
  desc: null
  value: 1
Sampling interval:
  desc: null
  value: 10000
Random seed eval:
  desc: null
  value: 7
Sampling:
  desc: null
  value: false
Crop eval:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692129002.951997
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.15.3
      8:
      - 5
      - 9
